### ISSUE TITLE
doc: improve readme to clearly state wagon usecases

### ISSUE THREAD

**Issue by sbinet** [go-interpreter/wagon#10]

**Comment by xyproto** [comment]
Yes, the description is a bit thin. After reading the README and project description I still have absolutely no clue what this can be used for. Is it for writing a webpage in Go that will then also use WebAssembly? It it for writing a faster and more encapsulated version of the Go playground? What is it for?

**Comment by sbinet** [comment]
@xyproto does go-interpreter/wagon#15 help?

**Comment by sbinet** [comment]
there is also more text other there:
 http://hepsoftwarefoundation.org/gsoc/proposal_GoInterpreterWagon.html

(the initial proposal for the GSoC internship)

**Comment by xyproto** [comment]
Yes, that's helpful. Thanks!
