### ISSUE TITLE
Would you accept PRs to implement a JIT?

### ISSUE THREAD

**Issue by twitchyliquid64** [go-interpreter/wagon#101]
Heya,

I would like to implement a JIT, starting with a subset of wasm instructions on amd64. Would you be open to accepting PRs?

To start with, the JIT would rewrite sequences of mathy instructions into a unit, which is referenced by PC. An unused opcode can be used to symbolize an execution of a jitted section.

For example:

```
LOAD i32
LOAD i32
ADD
LOAD i32
MUL
JMP blah
```
Could be rewritten to:

```
EXECJIT
NOP
NOP
NOP
NOP
JMP blah
```

`VM` would have a new `map` field, which would store JIT units using the PC as the index. Instructions which are rewritten into JIT code and rewritten to NOPs so the PC jumps remain the same.

Sufficiently long sequences of mathy code (which contain no branches and no inbound branches) will be JITed out, the rest left as-is.

This should eliminate mainloop + Go overhead for really tight, mathematics operations (such as hash computation). Once this works, I start supporting more opcodes, which will in turn mean more execution can be JIT accelerated. Given the VM already has a separate stack, I can avoid using any stack space (and hence avoid messing with Go's internal stack maps + management).

My testbest JIT can do this in linear time, using a greedy register allocation scheme.

Does this sound good to you?

**Comment by sbinet** [comment]
sounds really interesting!
(JITing Go is something I've always wanted to investigate...)

**Comment by twitchyliquid64** [comment]
Calling into JITed code is actually really easy, you just map in an executable page(s) and jump to it:

```go
fp := *(*func(uint64) uint64)(unsafe.Pointer(&f))
return fp(argument)
```

If the runtime happens to do a GC run, it wont recognize the current PC and will try again later. The only thing we have to worry about is stack overrun. I've also confirmed that planned pre-emptive scheduling will do the same thing.

We are guaranteed to have 720 bytes spare as long as we dont have any defers in our calling function (this is the red zone - a spare space buffer that the runtime maintains). If we need more, we can call into `runtime.morestack`, a check+call that appears in every Go function prologue.

The only hard bit left is generating the instructions & register selection. Ive pulled out the Go assembler into a library [here](https://github.com/twitchyliquid64/golang-asm), and have a reasonable linear-time JIT implemented in a private repo (which i will open eventually).

**Comment by twitchyliquid64** [comment]
Pinging this thread. I'm seeking explicit approval @sbinet to implement this, and confirmation that PRs will be reviewed & eventually merged.

My plan is roughly this:

1. 1st PR - Resize `wagon/wasm/operators.Op` & `vm.funcTable` table to 512, use an unassigned opcode to symbolize execution of a JIT section (See [here](https://github.com/WebAssembly/design/issues/1141) for discussion about reserving an opcode for JIT use - TLDR nothing reserved yet, but JIT opcode can be trivially moved as new instructions are added).

2. 2nd PR - Add `exec.NewVMWithOptions(*exec.VMOptions)` so VMs can be constructed with options passed in. The only options for now would be configuration for enabling JIT/AOT compilation. I would also lay out the boilerplate for the jit itself in `wagon/exec/jit`.

3. 3rd PR - Implement JIT for a restricted subset of instructions on x64.

Subsequent instructions would add support for more and more instructions, better register allocator etc.

**Comment by sbinet** [comment]
as I said earlier, JITing is definitely something I am interested in.
please proceed :)

**Comment by twitchyliquid64** [comment]
Closing as this is in progress.
