### ISSUE TITLE
How to solve `disasm: stack underflow` when call `exec.NewVM(module)`

### ISSUE THREAD

**Issue by yyh1102** [go-interpreter/wagon#140]
i try to exec the [wast](https://gist.github.com/yyh1102/2c76b4f3d19475059c635e1f3e9de776) file and get `disasm: stack underflow`. 

After i open `debugMode` and add extra logger print, and find out the error occurs in `ops.End or ops.Else` case:

![image](https://user-images.githubusercontent.com/10328169/61515819-15127d80-aa36-11e9-9b3e-e22a9e7afbeb.png)

curDepth is `-1`. prevDepth is `2`.  elemsDiscard is `-3`

![image](https://user-images.githubusercontent.com/10328169/61522980-0af87b00-aa46-11e9-8b16-beaaea4c46f0.png)

Seems like `set_local` op push `-1` to the top of stack. And then next op is `op.end`, makes the `curDepth = -1`, and `elemsDiscard` becomes `-3`, which throw `ErrStackUnderflow`. 

What are the possible problems for this error? How can i solve it?

**Comment by yyh1102** [comment]
Opened an [issue](https://github.com/AssemblyScript/assemblyscript/issues/723#issue-470964915) in assemblyscript and seems like this is the unexpected result of wagon.

**Comment by sbinet** [comment]
apologies for the belated answer (holidays).
@vibhavp would be the one with the most expertise on this.

(feel free to reopen if that's still an issue for you)
