### ISSUE TITLE
new validation refer to spec have multi bugs

### ISSUE THREAD

**Issue by carltraveler** [go-interpreter/wagon#173]
[testwasmdata_l.tar.gz](https://github.com/go-interpreter/wagon/files/3720246/testwasmdata_l.tar.gz)

use main.go in file. and test0.wat should not passed validation

**Comment by carltraveler** [comment]
other three file(bin.wasm, boa.wasm, jsvm.wasm) should be passed

**Comment by twitchyliquid64** [comment]
Are these tests from the official test suite or specification? If so, can you link them?

**Comment by carltraveler** [comment]
no, but these file can pass  wasm-validate which is the tool from [wabt](https://github.com/WebAssembly/wabt) . and test0.wat contruct by myself

**Comment by carltraveler** [comment]
if the if inst have no else branch. then can not have result.  because validation can not assert the conditon at static check stage

**Comment by twitchyliquid64** [comment]
Do you have a copy of the wast for those three files? I can't work with them or test in their compiled format.

I've improved validation around the ELSE block in #174, particularly:

 - Validating that IF blocks can only return a value if they have an ELSE block
 - Adding tests for this case and any other invariants I can think of for the if and else blocks.

wdyt?
