### ISSUE TITLE
Read leb128 fail when trying to read 64 bit of small number

### ISSUE THREAD

**Issue by anhcao142** [go-interpreter/wagon#175]
```golang
r := bytes.NewReader([]byte{0x08})
n, err := ReadUint64(r)
if err != nil {
  t.Fatal(err)
}
fmt.Println(n)
// output: leb128: invalid uint
```

**Comment by twitchyliquid64** [comment]
@sbinet are you familiar with the leb128 encoding?

**Comment by laizy** [comment]
@anhcao142 where is the `ReadUint64` defined? there are `ReadVarint64` and `ReadVarUint32` in package `leb128` , and they are works.

**Comment by anhcao142** [comment]
Sorry, my bad, I actually mean `ReadVarUint32` and let me check again

**Comment by anhcao142** [comment]
It's actually a mistake from my side, I'm sorry for troubling you. But before closing, can I ask why you don't have `ReadVarUint64` method?

**Comment by laizy** [comment]
@anhcao142 ,maybe it is not used currently? but `readVarUint(r io.Reader, n uint)` is a  general-purpose function for read `uintN`(like uint7, uint16), so you can define `ReadVarUint64` as :
```golang
func ReadVarUint64(r io.Reader) (uint64, error) {
	n, err := readVarUint(r, 64)
	if err != nil {
		return 0, err
	}
	return uint64(n), nil
}
```
