### ISSUE TITLE
Can I get a unexported function's name in wasm module?

### ISSUE THREAD

**Issue by zhangzhiqiangcs** [go-interpreter/wagon#183]
Like this, I can get a exported function's name for a Module named mod
``` mod.Export.Names ```
I wonder if I can get a unexported function's name ? Thanks for any suggestions.

**Comment by puuuuh** [comment]
Non-imported functions have no name

**Comment by zhangzhiqiangcs** [comment]
> Non-imported functions have no name

ok, Thank you!
