### ISSUE TITLE
Stack Underflow on valid wasm file

### ISSUE THREAD

**Issue by dignifiedquire** [go-interpreter/wagon#49]
I have this minimal example, which runs fine if I execute it with `wasm-interp`, but throws a `ErrStackUnderflow` if I try and execute it with wagon

Source:
```rust
#![allow(non_snake_case)]

use std::mem;
use std::collections::HashMap;

pub struct Sample {
    map: HashMap<u64, u64>,
}

impl Sample {
    pub fn new() -> Sample {
        Sample { map: HashMap::new() }
    }
}

#[no_mangle]
pub fn init() -> *mut Sample {
    let mut _s = unsafe { mem::transmute(Box::new(Sample::new())) };
    _s
}
```

wasm-intrep output
```
> wasm-interp token.wasm --run-all-exports
memory() => error: unreachable executed
init() => i32:1114496
```

Attached is the [token.wasm.zip](https://github.com/go-interpreter/wagon/files/1565101/token.wasm.zip)

**Comment by sbinet** [comment]
tentatively assigning this to @vibhavp as he has the most experience with the part of the code dealing with this.

also: do you think there could be a way to have a simpler reproducer? there are a lot of functions in there...

**Comment by dignifiedquire** [comment]
I got it a little smaller, but it seems this is coming from compiling some part of the rust std lib. 

```rust
#[no_mangle]
pub fn sample() -> usize {
    let mut v: Vec<usize> = Vec::new();
    v[0] = 1;
    v.len()
}
```

attached wasm and wast file

[Archive.zip](https://github.com/go-interpreter/wagon/files/1568194/Archive.zip)

**Comment by vibhavp** [comment]
I've pushed a fix to https://github.com/vibhavp/wagon/tree/fix-49, which should fix this. (although `wasm-run` cannot run specific functions, which will cause it to panic)

**Comment by dignifiedquire** [comment]
@vibhavp getting panics both when using `vm.ExecCode` as well with `wasm-run` now

```
> wasm-run token.wasm
    Finished release [optimized] target(s) in 0.0 secs
memory() => wasm-run: running exported functions with input parameters is not supported
sample() i32 => panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/go-interpreter/wagon/exec.(*VM).execCode(0xc42018c000, 0xc4200fc340, 0xe4, 0x193, 0x121fcd0, 0x0, 0x0, 0x16, 0x3, 0x0, ...)
	/Users/dignifiedquire/.go/src/github.com/go-interpreter/wagon/exec/vm.go:341 +0x719
github.com/go-interpreter/wagon/exec.(*VM).ExecCode(0xc42018c000, 0x1, 0x0, 0x0, 0x0, 0x10, 0x0, 0x0, 0xc420043e40)
	/Users/dignifiedquire/.go/src/github.com/go-interpreter/wagon/exec/vm.go:262 +0x1d5
main.main()
	/Users/dignifiedquire/.go/src/github.com/go-interpreter/wagon/cmd/wasm-run/main.go:79 +0x640
```

**Comment by vibhavp** [comment]
The panic is probably a result of `wasm-run` not being able to push arguments when calling functions that have parameters.

**Comment by sbinet** [comment]
Not sure about your assessment wrt wasm-run: it's supposed to discard (not
execute) exported functions that need input arguments.

I'll try to have a closer look before Saturday.

sent from my droid

**Comment by vibhavp** [comment]
@dignifiedquire I have updated my PR, could you test it again?

**Comment by dignifiedquire** [comment]
@vibhavp looking good, now working as expected
