### ISSUE TITLE
invalid number of arguments to function

### ISSUE THREAD

**Issue by SeavantUUz** [go-interpreter/wagon#83]
Hi, first thanks for your great work.

I met a strange behavior and got confuse whether it is a bug or excepted behavior.

The source is simple cpp codes as

```cpp
extern "C" {
    extern void print(int v);
    extern int iadd(int a, int b);
    int test(){
        int a = iadd(4,10);
        print(a);
        return 0;
    }
}
```

then I got a .wasm file, I pasted the .wast content below:

```wasm
(module
 (type $FUNCSIG$iii (func (param i32 i32) (result i32)))
 (type $FUNCSIG$vi (func (param i32)))
 (import "env" "iadd" (func $iadd (param i32 i32) (result i32)))
 (import "env" "print" (func $print (param i32)))
 (table 0 anyfunc)
 (memory $0 1)
 (data (i32.const 4) "\10@\00\00")
 (export "memory" (memory $0))
 (export "test" (func $test))
 (func $test (result i32)
  (call $print
   (call $iadd
    (i32.const 4)
    (i32.const 10)
   )
  )
  (i32.const 0)
 )
)
```

Following your `vm_example_test.go`, I tried these ( only `Types`, `FunctionIndexSpace`, `Export` below)

```go
var nativeFunctionList = []string{
	"print42",
	"print",
	"iadd",
}

var nativeFunctionTypes = &wasm.SectionTypes{
	Entries: []wasm.FunctionSig{
		{
			ParamTypes:  []wasm.ValueType{},
			ReturnTypes: []wasm.ValueType{},
		},
		{
			ParamTypes:  []wasm.ValueType{wasm.ValueTypeI32},
			ReturnTypes: []wasm.ValueType{},
		},
		{
			ParamTypes:  []wasm.ValueType{wasm.ValueTypeI32, wasm.ValueTypeI32},
			ReturnTypes: []wasm.ValueType{wasm.ValueTypeI32},
		},
	},
}

var nativeFunction = []wasm.Function{
	{
		Sig:  &nativeFunctionTypes.Entries[0],
		Host: reflect.ValueOf(func(proc *exec.Process) { fmt.Printf("result = 42\n") }),
		Body: &wasm.FunctionBody{},
	},
	{
		Sig:  &nativeFunctionTypes.Entries[1],
		Host: reflect.ValueOf(func(cos *exec.Process, v int32) { fmt.Printf("result = %v \n", v) }),
		Body: &wasm.FunctionBody{},
	},
	{
		Sig:  &nativeFunctionTypes.Entries[2],
		Host: reflect.ValueOf(func(proc *exec.Process, a int32, b int32) int32 { return a + b }),
		Body: &wasm.FunctionBody{},
	},
}
```

Look good, right?

But in the runtime, compiler complained: invalid number of arguments to function. And I found the print function, which was passed 0 args.

I tried to replace from ` int a = iadd(4,10);` to `int a = 4;`. It works well.

And I removed `print(a);`. It works well too.

Just look as the 

```wasm
   (call $iadd
    (i32.const 4)
    (i32.const 10)
   )
```

doesn't be treated  as the parameter to `print` function even the return type is int32 ?

**Comment by duanbing** [comment]
`print` needs one parameter `v int32`, declared in vm_example_test.go

**Comment by SeavantUUz** [comment]
@duanbing 

So you means my `iadd` function doesn't return a `int32`?

May I not express clearly? 

```cpp
int a = 4;
print(a);
```

it works

```cpp
int a = iadd(1, 3);
```

it works as well.

but 

```cpp
int a = iadd(1, 3);
print(a);
```

it can't be executed.

Of course I know the `print` excepts a `int32` and I am sure the return type of `iadd` is `int32`. Just took a glance of my content. I have defined below:

```wasm
	{
		Sig:  &nativeFunctionTypes.Entries[1],
		Host: reflect.ValueOf(func(cos *exec.Process, v int32) { fmt.Printf("result = %v \n", v) }),
		Body: &wasm.FunctionBody{},
	},
	{
		Sig:  &nativeFunctionTypes.Entries[2],
		Host: reflect.ValueOf(func(proc *exec.Process, a int32, b int32) int32 { return a + b }),
		Body: &wasm.FunctionBody{},
	},
```

the first Function is `print` and the next is `iadd`.

I guess you made a misunderstood, the `print` doesn't come from `vm_example_test.go`. It is defined by myself and I know what type it would be accepted.

So I got confused by the behavior which doesn't match what I had thought.

**Comment by duanbing** [comment]
Take a look [here](https://github.com/duanbing/wasm-test/blob/master/go/main.go), hope it's helpful.

**Comment by duanbing** [comment]
The `drop` operator can be used to explicitly pop a value from the stack.

**Comment by SeavantUUz** [comment]
@duanbing 

Exactly I know the behavior of drop. It popped the top of the stack, right. In the sample, it is the result of `iadd` function. But the `print` function:

```wasm
(call $print
   (i32.const 4)
  )
```

should have not told me the error info : *invalid number of arguments to function*

got it please. 

I did the mini wasm vm [here](https://gist.github.com/SeavantUUz/e4db693322d86235a45459fc5250e252). You can take a look *please*. It isn't as easy as you think maybe.

**Comment by SeavantUUz** [comment]
After debugging, and read [this](https://github.com/ethereum/go-ethereum/pull/16957/files) I finally noticed where I did wrong.

In the [implement](https://gist.github.com/SeavantUUz/e4db693322d86235a45459fc5250e252#file-coswasm-go-L39)

I forced the entry pointe to function index 1. When only `iadd` or `print` is called, the entry actually is 1 but when compose both, the entry index changed.

So I modified my codes as these:

```go
        var entryIndex = -1
	for name, entry := range module.Export.Entries {
		if name == "test" && entry.Kind == wasm.ExternalFunction {
			entryIndex = int(entry.Index)
		}
	}

	if entryIndex >= 0 {
		r, err := vm.ExecCode(int64(entryIndex))
		if err != nil {
			if err.Error() != "exec: return" && err.Error() != "exec: revert" && err.Error() != "exec: suicide" {
				fmt.Println(err)
				return nil, fmt.Errorf("Error excuting function %d: %v", 0, err)
			}
		}
		fmt.Println(r)
	}
```

look good.
