### ISSUE TITLE
What is this interpreter supposed to do?

### ISSUE THREAD

**Issue by SerkanSipahi** [go-interpreter/wagon#9]
What is wagon supposed to do?

Short questions:
1.) wagon can produce go to wasm?
2.) wagon can consume wasm code?

**Comment by sbinet** [comment]
1) is out of the scope of `wagon`.
2) definitely is the goal of this project.

here is the original GSoC proposal:
 - http://hepsoftwarefoundation.org/gsoc/proposal_GoInterpreterWagon.html

**Comment by pwaller** [comment]
I agree with @SerkanSipahi - the way it's currently written in the readme allows for both interpretations. Might be worth trying to find alternative less ambiguous language: "Wagon enables Go to parse and execute WebAssembly by interpreting it".

**Comment by sbinet** [comment]
will do. (I've created go-interpreter/wagon#10 for this.)

let's close this (and feel free to re-open if you disagree and/or use the go-interpreter mailing list for broader discussion: go-interpreter@googlegroups.com)

**Comment by SerkanSipahi** [comment]
@sbinet 
> 1.) is out of the scope of wagon.

:(

**Comment by sbinet** [comment]
Progress and plans for 1) are reported here: golang/go#18892
